/**
 * Writes public/favicon.svg from an icon in the installed sets.
 *
 * The icon is lifted from `@iconify-json/icon-park-outline` and recoloured, not redrawn here.
 * That is the rule for every icon in this app: they come from a set so they stay consistent with each other and so nobody has to maintain hand written path data.
 *
 * Run after changing ICON or COLOUR:
 *
 *   node scripts/build-favicon.ts
 */
import { readFile, writeFile } from 'node:fs/promises';

/** The same mandarin the header and the rating use. */
const ICON = 'orange';
const COLOUR = '#e35205';
const SET = 'node_modules/@iconify-json/icon-park-outline/icons.json';

interface IconSet {
  width?: number;
  height?: number;
  icons: Record<string, { body: string; width?: number; height?: number }>;
}

const set: IconSet = JSON.parse(await readFile(SET, 'utf8'));
const icon = set.icons[ICON];

if (!icon) {
  throw new Error(`Icon "${ICON}" is not in ${SET}`);
}

const width = icon.width ?? set.width ?? 24;
const height = icon.height ?? set.height ?? 24;

// IconPark draws with currentColor plus a hardcoded fill for the solid parts.
// Both become the mandarin, so the favicon reads the same on any background.
const body = icon.body.replaceAll('currentColor', COLOUR).replaceAll('fill="#333"', `fill="${COLOUR}"`);

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <!-- Generated by scripts/build-favicon.ts from icon-park-outline "${ICON}" (MIT). Recoloured, not redrawn. -->
  ${body}
</svg>
`;

await writeFile('public/favicon.svg', svg, 'utf8');
console.log(`Wrote public/favicon.svg from icon-park-outline "${ICON}"`);
